### ISSUE TITLE
User Account Integration.

### ISSUE THREAD

**Issue by OpenOS-Project-Creator-Founder** [rosineygp/symbiosOS#1]
https://github.com/Seshpenguin/mulxd/issues/2

**Comment by rosineygp** [comment]
@OpenOS-Project-Creator-Founder sorry man, I don't understand the problem...

would you like symbiosOS integrated with KDE?

**Comment by OpenOS-Project-Creator-Founder** [comment]
> @OpenOS-Project-Creator-Founder sorry man, I don't understand the problem...
> 
> would you like symbiosOS integrated with KDE?

Not only with KDE but Gnome also.

To create a lxc/lxd container that's associated & linked & symlinked & rsynced through the restful api or something to have a live stream or host the individual user accounts as the container contents internal data.

**Comment by rosineygp** [comment]
It's too much to me, feel free to fork and implement

thanks for share your ideia!!!
